// SPDX-License-Identifier: AGPL-3.0-only
import { defineCollection, z } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// The docs collection is generated by tools/website-docs.mjs from the manifest-selected
// repository Markdown. Provenance travels in front matter so the footer can name the
// exact maintained source.
export const collections = {
  docs: defineCollection({
    loader: docsLoader(),
    schema: docsSchema({
      extend: z.object({
        diffdevil: z.object({ source: z.string(), sourceUrl: z.string(), appliesTo: z.string(), tested: z.boolean() }).optional(),
      }),
    }),
  }),
};
