import { createHash } from 'node:crypto';
import { cp, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { stringify } from 'yaml';
import { ACTION_INPUTS, ENTRY_POINTS, NUMERIC_OUTPUTS, REPORT_OUTPUTS, PLAN_OUTPUTS, EFFECT_OUTPUTS, inputNames, outputNames } from '../dist/lib/actions/surface.js';

// Native Node resolution is the packager. No module transformation, global tool, install or network.
const root = fileURLToPath(new URL('..', import.meta.url));
const check = process.argv.includes('--check');
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
async function files(directory) {
  const found = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) throw new Error(`Distribution input contains a symlink: ${join(directory, entry.name)}`);
    if (entry.isDirectory()) found.push(...await files(join(directory, entry.name)));
    else if (entry.isFile()) found.push(join(directory, entry.name));
    else throw new Error(`Distribution input is not a regular file: ${join(directory, entry.name)}`);
  }
  return found.sort();
}
const temporary = await mkdtemp(join(tmpdir(), 'diffdevil action build '));
const runtime = join(temporary, 'action-runtime');
try {
  const lock = JSON.parse(await readFile(join(root, 'package-lock.json'), 'utf8'));
  const project = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
  await mkdir(join(runtime, 'lib'), { recursive: true });
  for (const path of await files(join(root, 'dist/lib'))) {
    if (!/\.(?:js|cjs|mjs)(?:\.map)?$/u.test(path)) continue;
    const to = join(runtime, 'lib', relative(join(root, 'dist/lib'), path));
    await mkdir(resolve(to, '..'), { recursive: true }); await cp(path, to);
  }
  const dependencies = [];
  for (const [path, resolved] of Object.entries(lock.packages).sort(([a], [b]) => a.localeCompare(b, 'en'))) {
    if (!path || resolved.dev || resolved.devOptional) continue;
    if (!/^node_modules\/(?:@[a-z0-9._-]+\/)?[a-z0-9._-]+(?:\/node_modules\/(?:@[a-z0-9._-]+\/)?[a-z0-9._-]+)*$/u.test(path) || resolved.link) throw new Error(`Unsupported locked package path: ${path}`);
    const packageRoot = join(root, path), manifest = JSON.parse(await readFile(join(packageRoot, 'package.json'), 'utf8'));
    if (manifest.version !== resolved.version) throw new Error(`Installed ${path} does not match its lock. Restore the locked dependency closure.`);
    const owned = (await files(packageRoot)).filter(file => !relative(packageRoot, file).split(/[\\/]/u).includes('node_modules'));
    const notices = owned.filter(file => /^(?:licen[cs]e|notice|copying)(?:[.-]|$)/iu.test(relative(packageRoot, file).split(/[\\/]/u).at(-1)));
    if (!notices.length) throw new Error(`No redistribution notice found in ${path}; review before shipping.`);
    for (const file of owned) {
      const to = join(runtime, path, relative(packageRoot, file));
      await mkdir(resolve(to, '..'), { recursive: true }); await cp(file, to);
    }
    dependencies.push({ name: manifest.name, version: manifest.version, license: manifest.license ?? resolved.license,
      integrity: resolved.integrity, path, notices: notices.map(file => relative(packageRoot, file).replaceAll('\\', '/')) });
  }
  await writeFile(join(runtime, 'package.json'), JSON.stringify({ name: 'diffdevil-action-runtime', private: true, type: 'module', version: project.version,
    license: project.license, engines: { node: '>=24' }, description: 'Generated install-free native ESM distribution for all four diffdevil Actions.' }, null, 2) + '\n');
  await writeFile(join(runtime, 'README.md'), '# diffdevil Action runtime\n\n## Meaning\n\nGenerated, install-free native ESM distribution shared by all four Actions. It contains compiled diffdevil code, standalone schema validators, and the exact locked runtime package trees with their redistribution notices. It is not a single-file minified bundle.\n\nRegenerate with `npm run build:actions`; verify tracked bytes with `npm run check:actions`. Do not edit generated files here. The root project licence remains unselected; dependency notices do not select one. See `../docs/integration/action-distribution.md` for the build and consumer boundaries.\n');
  for (const entry of ENTRY_POINTS) {
    const directory = entry === 'root' ? temporary : join(temporary, entry);
    await mkdir(directory, { recursive: true });
    if (entry !== 'root') await writeFile(join(directory, 'index.mjs'), `// Generated by scripts/build-actions.mjs; all behavior lives in the shared runtime.\nimport '../action-runtime/lib/actions/${entry}.js';\n`);
    const metadata = {
      name: entry === 'root' ? 'diffdevil' : `diffdevil — ${entry}`,
      description: entry === 'root' ? 'Measure pull-request changes, evaluate rules, and reconcile selected labels and comments.' : entry === 'analyze' ? 'Read-only pull-request facts, metrics, bands and decisions.' : entry === 'apply' ? 'Revalidate trusted policy and fresh facts before applying selected pull-request effects.' : 'Verify or explicitly reconcile declared repository label definitions.',
      author: 'Wolfsblvt',
      inputs: Object.fromEntries(inputNames(entry).map(name => { const { description, default: fallback } = ACTION_INPUTS[name]; return [name, { description, required: false, ...(fallback === undefined ? {} : { default: fallback }) }]; })),
      outputs: Object.fromEntries(outputNames(entry).map(name => [name, { description: name === 'report-json' ? 'Compact diffdevil.action-report-summary, not a full report. Full JSON is at report-path.' : name === 'plan-json' ? 'Compact diffdevil.action-plan-summary, not an executable plan. Full JSON is at plan-path.' : name === 'effects-changed' ? 'Count of operations with verified changed readback; empty when effects were not applied.' : `${name}; see the Action manual for exact, bounded, unavailable and not-applied values.` }])),
      runs: { using: 'node24', main: entry === 'root' ? 'action-runtime/lib/actions/root.js' : 'index.mjs' },
      branding: { icon: 'check-circle', color: 'gray-dark' },
    };
    await writeFile(join(directory, 'action.yml'), '# Generated from src/actions/surface.ts by npm run build:actions.\n' + stringify(metadata, { lineWidth: 110 }));
  }
  const catalog = JSON.parse(await readFile(join(root, 'spec/detail/v1/action-surface.json'), 'utf8'));
  catalog.standing = 'Implemented shared Action surface; local qualification is recorded in docs/QUALIFICATION.md. No publication or live-GitHub claim.';
  catalog.inputs = Object.keys(ACTION_INPUTS);
  catalog.inputEntryPoints = Object.fromEntries(Object.entries(ACTION_INPUTS).map(([key, value]) => [key, value.entries]));
  catalog.outputArtifactDestinations = ['report-path', 'plan-path', 'effects-path'];
  catalog.numericOutputBases = [...NUMERIC_OUTPUTS];
  catalog.otherOutputs = [...REPORT_OUTPUTS.filter(name => !NUMERIC_OUTPUTS.some(base => name === base || name.startsWith(base + '-'))), ...PLAN_OUTPUTS, ...EFFECT_OUTPUTS];
  catalog.entryPointOutputs = Object.fromEntries(ENTRY_POINTS.map(entry => [entry, outputNames(entry)]));
  await mkdir(join(temporary, 'spec/detail/v1'), { recursive: true });
  await writeFile(join(temporary, 'spec/detail/v1/action-surface.json'), JSON.stringify(catalog, null, 2) + '\n');
  const sourceFiles = [...await files(join(root, 'src')), ...await files(join(root, 'schemas')),
    ...['spec/detail/v1/ast.schema.json', 'spec/detail/v1/values.schema.json', 'presets/size-v1.yml', 'tsconfig.json', 'package.json', 'package-lock.json', 'scripts/build.mjs', 'scripts/schema-build.mjs', 'scripts/build-actions.mjs'].map(path => join(root, path))];
  const sources = {};
  for (const path of sourceFiles.sort()) sources[relative(root, path).replaceAll('\\', '/')] = sha256(await readFile(path));
  const shipped = {};
  for (const path of await files(temporary)) shipped[relative(temporary, path).replaceAll('\\', '/')] = sha256(await readFile(path));
  await writeFile(join(runtime, 'MANIFEST.json'), JSON.stringify({ kind: 'diffdevil.action-distribution', schemaVersion: '1.0', format: 'native-esm-closure', target: 'node24',
    compiler: lock.packages['node_modules/typescript'].version, dependencies, sources, files: shipped }, null, 2) + '\n');
  if (check) {
    const expected = (await files(temporary)).map(path => relative(temporary, path));
    const actualRuntime = (await files(join(root, 'action-runtime'))).map(path => relative(root, path));
    if (actualRuntime.some(path => !expected.includes(path))) throw new Error('Unexpected file in tracked Action distribution. Rebuild and inspect.');
    for (const path of expected) {
      const [expectedBytes, actualBytes] = await Promise.all([readFile(join(temporary, path)), readFile(join(root, path))]);
      if (!expectedBytes.equals(actualBytes)) throw new Error(`Stale generated Action file: ${path}. Run npm run build:actions and inspect the diff.`);
    }
    console.log(`Action distribution is current: ${expected.length} generated files; ${dependencies.length} locked runtime packages; node24.`);
  } else {
    await rm(join(root, 'action-runtime'), { recursive: true, force: true });
    for (const path of await files(temporary)) {
      const to = join(root, relative(temporary, path)); await mkdir(resolve(to, '..'), { recursive: true }); await cp(path, to);
    }
    console.log(`Built install-free Action distribution: ${Object.keys(shipped).length + 1} generated files; ${dependencies.length} locked runtime packages; node24.`);
  }
} finally { await rm(temporary, { recursive: true, force: true }); }
