// SPDX-License-Identifier: AGPL-3.0-only
/**
 * Project the App's icon meanings to a small generated module from the installed Lucide and
 * Simple Icons collections, the same sources the website's registry reads at build time.
 * The App renders on a Worker, where the whole collection must not be bundled, so only the
 * named glyphs are written. Add a meaning here before using it in the App.
 */
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const require = createRequire(import.meta.url);
const lucide = require('@iconify-json/lucide/icons.json');
const simple = require('@iconify-json/simple-icons/icons.json');

/** semantic name → `<route>:<id>` */
const meanings = {
  overview: 'ui:layout-dashboard', 'pull-request': 'ui:git-pull-request', 'pull-request-draft': 'ui:git-pull-request-draft', merged: 'ui:git-merge', 'pull-request-closed': 'ui:git-pull-request-closed',
  history: 'ui:history', files: 'ui:files', manage: 'ui:settings-2', chevron: 'ui:chevron-down', lock: 'ui:lock', book: 'ui:book', refresh: 'ui:refresh-cw',
  search: 'ui:search', external: 'ui:external-link', 'arrow-right': 'ui:arrow-right', check: 'ui:check', filter: 'ui:list-filter', open: 'ui:maximize-2',
  'circle-dashed': 'ui:circle-dashed', organization: 'ui:building', user: 'ui:user', 'log-out': 'ui:log-out', github: 'brand:github'
};

const bodies = {};
for (const [name, selector] of Object.entries(meanings)) {
  const [route, id] = selector.split(':');
  // Lucide renames keep the old name as an alias; resolve one level of alias before giving up.
  const resolve = (collection, key) => collection.icons[key] ?? collection.icons[collection.aliases?.[key]?.parent];
  const body = (route === 'ui' ? resolve(lucide, id) : resolve(simple, id))?.body;
  if (!body) throw new Error(`App icon "${name}" (${selector}) is not in its installed collection.`);
  bodies[name] = body;
}
const target = resolve('apps/app/src/generated/icons.mjs');
mkdirSync(resolve('apps/app/src/generated'), { recursive: true });
writeFileSync(target, `// Generated by tools/app-icons.mjs from the installed icon collections. Do not edit.\nexport const ICONS = ${JSON.stringify(bodies, null, 2)};\n`);
console.log(`Wrote ${Object.keys(bodies).length} App icons to ${target}`);
