// SPDX-License-Identifier: AGPL-3.0-only
import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { productionModules, memoryAreas, comparison, patch, unwrap, metadata, response } from './support.mjs';
const loaded = await productionModules(); after(loaded.cleanup);
const m = loaded.module;
const defaults = () => ({ ...m.DEFAULTS });
const report = () => unwrap(m.analyzeBrowserInput(JSON.stringify({ comparison, format: 'diff', text: patch, complete: true })));
const personal = settings => unwrap(m.compileBrowserPolicy(JSON.stringify({ mode: 'personal-only', personal: m.personalYaml(settings) })));

test('every public setting has one unique dotted ID and a default', () => {
  assert.equal(new Set(m.SETTINGS.map(item => item.id)).size, m.SETTINGS.length);
  for (const item of m.SETTINGS) { assert.match(item.id, /^[a-z]+\.[A-Za-z]+$/u); assert.ok(item.name); assert.ok(item.description); if (item.kind !== 'action') assert.equal(typeof item.default, typeof m.DEFAULTS[item.id]); }
});
test('default settings compile the real Changed policy, not raw churn', () => { const config = m.validateSettings({}); const view = unwrap(m.humanReport(report(), personal(config))); assert.equal(view.changed.value, 2); assert.equal(view.raw.churn.value, 3); assert.equal(view.report.metrics.review.value, 2); assert.equal(view.rails[0].cells.length, 5); });
test('rendering preferences are the grammar’s two: the icon and GitHub’s raw churn, hidden by default', () => { assert.deepEqual(m.SETTINGS.filter(item => item.id.startsWith('display.')).map(item => item.id), ['display.enabled', 'display.brandIcon', 'display.nativeChurn']); assert.equal(m.DEFAULTS['display.nativeChurn'], 'hidden'); assert.equal(m.validateSettings({ 'display.nativeChurn': 'faint' })['display.nativeChurn'], 'faint'); assert.throws(() => m.validateSettings({ 'display.rawChurn': true })); });
test('rendering preferences are the grammar’s two: the icon and GitHub’s raw churn, hidden by default', () => { assert.deepEqual(m.SETTINGS.filter(item => item.id.startsWith('display.')).map(item => item.id), ['display.enabled', 'display.brandIcon', 'display.nativeChurn']); assert.equal(m.DEFAULTS['display.nativeChurn'], 'hidden'); assert.equal(m.validateSettings({ 'display.nativeChurn': 'faint' })['display.nativeChurn'], 'faint'); assert.throws(() => m.validateSettings({ 'display.rawChurn': true })); });
test('icon is default-on monochrome and none is a valid explicit choice', () => { assert.equal(m.DEFAULTS['display.brandIcon'], 'monochrome'); assert.equal(m.validateSettings({ 'display.brandIcon': 'none' })['display.brandIcon'], 'none'); assert.throws(() => m.validateSettings({ 'display.brandIcon': 'anything' })); });
test('monochrome icon bytes are the accepted centre-seam shared glyph', async () => { const bytes = await readFile('apps/browser-extension/assets/diffdevil-brand.svg'); assert.equal(createHash('sha256').update(bytes).digest('hex'), 'd33cf3b1a7a8ec52706da3311ac82e0500ec6c2eee8e35baeaaa2d5ef2b9b34e'); const manifest = JSON.parse(await readFile('apps/browser-extension/manifest.json', 'utf8')); assert.ok(manifest.web_accessible_resources[0].resources.includes('assets/diffdevil-brand.svg')); });
test('search includes stable IDs and hidden Advanced descriptions', () => { assert.equal(m.searchSettings('#labels.nativeHandoff')[0].id, 'labels.nativeHandoff'); assert.ok(m.searchSettings('@advanced policy').every(item => item.advanced)); assert.ok(m.searchSettings('native picker').some(item => item.id === 'labels.nativeHandoff')); });
test('advanced modification count is not a second settings state', () => { const settings = m.validateSettings({ 'labels.nativeHandoff': false, 'display.enabled': false }); assert.deepEqual(m.advancedChanges(settings).map(item => item.id), ['labels.nativeHandoff']); assert.deepEqual(m.searchSettings('@modified', settings).map(item => item.id).sort(), ['display.enabled', 'labels.nativeHandoff']); });
test('unknown keys, wrong types and cache limits are rejected', () => { for (const value of [{ typo: true }, { 'display.enabled': 'false' }, { 'cache.maximumSize': 3 }, { 'cache.maximumSize': 129 }, { 'cache.maximumSize': 4.5 }]) assert.throws(() => m.validateSettings(value)); });
test('repository keys support .github and underscores but not traversal', () => { assert.equal(m.repositoryKey('Wolf/.GitHub'), 'wolf/.github'); assert.equal(m.repositoryKey('wolf/_internal'), 'wolf/_internal'); for (const value of ['../x', 'a/..', 'https://github.com/a/b', 'a/b/c', 'a\\b']) assert.throws(() => m.repositoryKey(value)); });
test('band shape enforces strict thresholds and unique normalized labels', () => {
  const values = m.bands(m.DEFAULT_BANDS); values[1].lt = values[0].lt; assert.throws(() => m.bands(JSON.stringify(values)));
  const names = m.bands(m.DEFAULT_BANDS); names[0].label = 'same'; names[1].label = ' same '; assert.throws(() => m.bands(JSON.stringify(names)));
  const final = m.bands(m.DEFAULT_BANDS); final.at(-1).lt = 10000; assert.throws(() => m.bands(JSON.stringify(final)));
});
test('partial native label mappings stay visible without manufacturing a provider plan', () => {
  const values = m.bands(m.DEFAULT_BANDS); values[2].label = ''; values[0].name = 'Tiny';
  const settings = m.validateSettings({ 'policy.bands': JSON.stringify(values) });
  const view = m.decorateView(unwrap(m.humanReport(report(), personal(settings))), settings);
  assert.equal(view.rails[0].cells[0].name, 'Tiny'); assert.equal(view.rails[0].label, 'size/XS'); assert.ok(view.rails[0].members.includes('size/XS')); assert.equal(Object.keys(view.report.rules ?? {}).length, 0);
});
test('classification metric changes do not rename or replace Changed', () => { const settings = m.validateSettings({ 'policy.primaryMetric': 'raw.churn' }); const view = unwrap(m.humanReport(report(), personal(settings))); assert.equal(view.changed.value, 2); assert.equal(view.report.metrics.review.value, 3); });
test('Advanced YAML replaces the guided personal document without erasing it', () => { const yaml = 'version: 1\nsize:\n  metric: raw.churn\n'; const settings = m.validateSettings({ 'policy.advancedYaml': yaml }); assert.equal(m.personalYaml(settings), yaml); assert.equal(settings['policy.bands'], m.DEFAULT_BANDS); assert.equal(unwrap(m.humanReport(report(), personal(settings))).report.metrics.review.value, 3); });
test('invalid Advanced YAML cannot be saved', () => { assert.throws(() => m.validateSettings({ 'policy.advancedYaml': 'version: 1\nnonexistent: true\n' })); });
test('template files may be unresolved while editing but retain real compiler diagnostics', () => { const yaml = 'version: 1\nrules:\n  note:\n    when: "true"\n    effects:\n      comment:\n        mode: upsert\n        templateFile: .github/note.md\n'; assert.equal(m.validateSettings({ 'policy.advancedYaml': yaml })['policy.advancedYaml'], yaml); assert.equal(m.compileBrowserPolicy(JSON.stringify({ mode: 'personal-only', personal: yaml })).ok, false); });
test('repository overrides remain explicit and case-normalized', () => { const settings = m.validateSettings({ 'policy.repositoryOverrides': JSON.stringify({ 'Fixture/Example': { mode: 'personal-only', yaml: 'version: 1\n' } }) }); assert.equal(m.selectedPolicy(settings, 'fixture/example').mode, 'personal-only'); assert.equal(m.selectedPolicy(settings, 'different/example').mode, 'composed'); });
test('duplicate repository identities and unsupported fields are rejected', () => { assert.throws(() => m.overrides('{"a/b":{},"A/B":{}}')); assert.throws(() => m.overrides('{"a/b":{"token":"secret"}}')); });
test('upper repository convenience policy wins over guided lower declarations', () => { const policy = unwrap(m.compileBrowserPolicy(JSON.stringify({ mode: 'composed', personal: m.personalYaml(defaults()), repository: 'version: 1\nsize:\n  metric: raw.churn\n' }))); const view = m.decorateView(unwrap(m.humanReport(report(), policy)), defaults()); assert.equal(view.report.metrics.review.value, 3); assert.equal(view.policy.origins.find(origin => origin.path === '/metrics/review').layer, 'repository'); });

test('preferences split private policy into local storage and small preferences into sync', async () => {
  const areas = memoryAreas(); const preferences = new m.Preferences(areas); await preferences.save({ 'policy.advancedYaml': 'version: 1\n', 'policy.repositoryOverrides': '{"private/repository":{"mode":"personal-only"}}' });
  assert.equal(areas.sync.data[m.SETTINGS_KEY]['policy.advancedYaml'], undefined); assert.equal(areas.sync.data[m.SETTINGS_KEY]['policy.repositoryOverrides'], undefined); assert.equal(areas.local.data[m.SETTINGS_KEY]['policy.advancedYaml'], 'version: 1\n');
});
test('concurrent writes are serialized without losing a field', async () => { const preferences = new m.Preferences(memoryAreas()); await Promise.all([preferences.save({ 'display.enabled': false }), preferences.save({ 'display.nativeChurn': 'faint' })]); const settings = await preferences.load(); assert.equal(settings['display.enabled'], false); assert.equal(settings['display.nativeChurn'], 'faint'); });
test('sync quota failure rolls both stores back', async () => { const areas = memoryAreas(); const preferences = new m.Preferences(areas); await preferences.save({ 'display.enabled': false }); const previous = structuredClone(areas.local.data); areas.sync.failures = 1; await assert.rejects(preferences.save({ 'display.enabled': true, 'policy.advancedYaml': 'version: 1\n' })); assert.equal((await preferences.load())['display.enabled'], false); assert.deepEqual(areas.local.data, previous); });
test('failed rollback preserves a recovery journal until a later restart', async () => { const areas = memoryAreas(); const preferences = new m.Preferences(areas); await preferences.save({ 'display.enabled': false }); areas.sync.failures = 2; await assert.rejects(preferences.save({ 'display.enabled': true }), /recovery remains pending/); assert.ok(areas.local.data['diffdevil.settings.pending.v1']); const restarted = new m.Preferences(areas); assert.equal((await restarted.load())['display.enabled'], false); assert.equal(areas.local.data['diffdevil.settings.pending.v1'], undefined); });
test('interrupted settings commit restores the last committed pair', async () => { const areas = memoryAreas(); const preferences = new m.Preferences(areas); await preferences.save({ 'display.enabled': false }); const sync = structuredClone(areas.sync.data[m.SETTINGS_KEY]); const local = structuredClone(areas.local.data[m.SETTINGS_KEY]); areas.local.data['diffdevil.settings.pending.v1'] = { version: 1, sync, local }; areas.local.data[m.SETTINGS_KEY]['policy.advancedYaml'] = 'broken: true'; const restarted = new m.Preferences(areas); assert.equal((await restarted.load())['policy.advancedYaml'], ''); });
test('damaged persisted settings and journals fail without silent reset', async () => { const areas = memoryAreas(); areas.sync.data[m.SETTINGS_KEY] = []; await assert.rejects(new m.Preferences(areas).load(), /damaged/); assert.deepEqual(areas.sync.data[m.SETTINGS_KEY], []); areas.sync.data = {}; areas.local.data['diffdevil.settings.pending.v1'] = { version: 99 }; await assert.rejects(new m.Preferences(areas).load(), /journal/); });
test('settings reset clears local, synced, and session state', async () => { const areas = memoryAreas(); const preferences = new m.Preferences(areas); await preferences.save({ 'display.enabled': false }); areas.session.data.last = 'private'; await preferences.reset(); assert.deepEqual(areas.sync.data, {}); assert.deepEqual(areas.local.data, {}); assert.deepEqual(areas.session.data, {}); assert.equal((await preferences.load())['display.enabled'], true); });

const entry = (key, size, touched) => ({ key, size, touched, kind: 'report', value: {} });
test('LRU eviction preserves newest entries and handles replacement accounting', () => { const entries = [entry('a', 4, 1), entry('b', 4, 2), entry('c', 4, 3)]; assert.deepEqual(m.evictions(entries, 8), ['a']); assert.deepEqual(m.evictions(entries, 8, entry('b', 5, 4)), ['a', 'c']); });
test('LRU eviction is deterministic and never mutates the existing catalogue', () => { const values = [entry('z', 5, 1), entry('a', 5, 1)]; const before = structuredClone(values); assert.deepEqual(m.evictions(values, 5), ['a']); assert.deepEqual(values, before); });
test('budget decisions preserve the maximum over a sweep of entry sizes', () => { for (let count = 0; count < 100; count++) { const entries = Array.from({ length: count }, (_, i) => entry(String(i), (i * 997) % 1000 + 1, i)); const removed = new Set(m.evictions(entries, 5000)); assert.ok(entries.filter(item => !removed.has(item.key)).reduce((sum, item) => sum + item.size, 0) <= 5000); } });
test('invalid cache capacity is rejected before opening IndexedDB', async () => { const cache = new m.AnalysisCache({ open() { throw new Error('must not open'); } }); await assert.rejects(cache.configure(3), /4–128/); await assert.rejects(cache.configure(NaN), /4–128/); });

const sender = { id: 'owned', frameId: 0, url: 'https://github.com/fixture/example/pull/42/files', tab: { id: 7, url: 'https://github.com/fixture/example/pull/42/files' } };
test('only the owned extension options page can mutate settings', () => { assert.throws(() => m.authorize(sender, { type: 'settings.save', patch: {} }, 'owned'), /Settings/); assert.equal(m.authorize({ id: 'owned', url: 'chrome-extension://owned/options.html' }, { type: 'settings.save', patch: {} }, 'owned').options, true); });
test('messages from websites, other extensions and subframes are rejected', () => { for (const candidate of [{ ...sender, id: 'other' }, { ...sender, url: 'https://evil.test' }, { ...sender, tab: { url: 'https://evil.test/fixture/example/pull/42' } }, { ...sender, tab: undefined }, { ...sender, frameId: 1 }, { ...sender, url: 'chrome-extension://other/options.html' }]) assert.throws(() => m.authorize(candidate, { type: 'settings.get' }, 'owned')); });
test('current tab route authorizes direct loads and GitHub soft navigation without crossing PR scope', () => {
  assert.equal(m.authorize(sender, { type: 'settings.get' }, 'owned').pullRequest, 42);
  const moved = { ...sender, tab: { id: 7, url: 'https://github.com/fixture/next/pull/17/files' } };
  assert.equal(m.authorize(moved, { type: 'source.public', repository: 'fixture/next', pullRequest: 17 }, 'owned').pullRequest, 17);
  assert.throws(() => m.authorize(moved, { type: 'source.public', repository: 'fixture/example', pullRequest: 42 }, 'owned'), error => error.code === 'SENDER_SCOPE');
  const event = m.operationDiagnostic(new m.ExtensionError('SENDER_SCOPE', 'private URL'), 'source.public', { ...moved, documentId: 'document-7' });
  assert.deepEqual({ code: event.code, phase: event.phase, frameId: event.frameId, documentId: event.documentId, senderUrl: event.senderUrl, tabUrl: event.tabUrl, routeAgreement: event.routeAgreement }, { code: 'SENDER_SCOPE', phase: 'source.public', frameId: 0, documentId: 'document-7', senderUrl: 'github-pr', tabUrl: 'github-pr', routeAgreement: 'different' });
  assert.ok(!JSON.stringify(event).includes('fixture'));
});
test('a PR page cannot become an arbitrary repository source proxy', () => { assert.throws(() => m.authorize(sender, { type: 'source.public', repository: 'private/other', pullRequest: 42 }, 'owned')); assert.throws(() => m.authorize(sender, { type: 'source.public', repository: 'fixture/example', pullRequest: 43 }, 'owned')); assert.equal(m.authorize(sender, { type: 'cache.lookup', comparison }, 'owned').pullRequest, 42); });
test('policy paths are data with no absolute, parent or backslash escape', () => { for (const path of ['../secret', '/etc/passwd', 'a/../b', 'a\\b', 'a//b', '.']) assert.throws(() => m.safePath(path)); assert.equal(m.safePath('.github/a b.md'), '.github/a%20b.md'); });
test('file-tree counters bind to their file through GitHub’s diff anchor, the SHA-256 of the path', async () => { const anchors = await m.pathAnchors(['apps/github-app/README.md', 'src/cache.ts']); assert.equal(anchors.get('6fc13d762cf5e910fa06edbf29d002aa0096e40733743834db6b82cf4596a63e'), 'apps/github-app/README.md'); assert.equal(anchors.size, 2); });
test('route parsing covers tabs, .github repositories, and rejects foreign hosts', () => { for (const tab of ['', '/files', '/commits', '/checks']) assert.equal(m.route(`https://github.com/fixture/example/pull/42${tab}`).pullRequest, 42); assert.equal(m.route('https://github.com/fixture/.github/pull/1').repository, 'fixture/.github'); for (const url of ['https://evil.test/fixture/example/pull/42', 'https://github.com/fixture/example/issues/42', 'https://github.com/fixture/example/pull/0']) assert.equal(m.route(url), undefined); });

test('public acquisition uses read-only anonymous requests and verifies revisions twice', async () => {
  const calls = []; const source = new m.PublicSource(async (url, init) => { calls.push({ url, init }); return response(url.includes('/files?') ? [{ filename: 'a.ts', status: 'modified', additions: 2, deletions: 1, patch: '@@ -1,2 +1,3 @@\n-old\n+new\n+extra\n keep' }] : metadata()); });
  const result = await source.pull('fixture/example', 42, true); assert.equal(result.files.length, 1); assert.equal(calls.length, 3);
  for (const { url, init } of calls) { assert.ok(url.startsWith('https://api.github.com/repos/fixture/example/')); assert.equal(init.credentials, 'omit'); assert.equal(init.method, undefined); assert.equal(init.redirect, 'error'); assert.equal(init.headers.Authorization, undefined); }
});
test('default public acquisition keeps the browser-global fetch receiver', async () => {
  const originalFetch = globalThis.fetch; const receivers = [];
  globalThis.fetch = function () { receivers.push(this); return Promise.resolve(response(metadata())); };
  try {
    const result = await new m.PublicSource().pull('fixture/example', 42);
    assert.equal(result.comparison.head, comparison.head); assert.deepEqual(receivers, [globalThis]);
  } finally { globalThis.fetch = originalFetch; }
});
test('public file pagination is capped at GitHub’s 3,000-file ceiling', async () => {
  let pages = 0; const source = new m.PublicSource(async url => url.includes('/files?') ? (pages++, response(Array.from({ length: 100 }, (_, i) => ({ filename: `${pages}-${i}` })))) : response(metadata({ changed_files: 3001 })));
  const result = await source.pull('fixture/example', 42, true); assert.equal(pages, 30); assert.equal(result.files.length, 3000); assert.equal(result.comparison.changedFiles, 3001);
});
test('head movement during API pagination cannot become a current report', async () => { let reads = 0; const source = new m.PublicSource(async url => response(url.includes('/files?') ? [{ filename: 'a' }] : metadata({ head: { sha: reads++ ? 'c'.repeat(40) : comparison.head } }))); await assert.rejects(source.pull('fixture/example', 42, true), error => error.code === 'COMPARISON_MOVED'); });
test('foreign provider PR identity and invalid counters are rejected', async () => { for (const value of [metadata({ number: 43 }), metadata({ changed_files: -1 }), metadata({ base: { sha: comparison.base, repo: { full_name: 'other/repo' } } })]) await assert.rejects(new m.PublicSource(async () => response(value)).pull('fixture/example', 42)); });
test('private and rate-limited API responses have explicit distinct failures', async () => { for (const [status, code] of [[404, 'PUBLIC_UNAVAILABLE'], [403, 'GITHUB_RATE_LIMIT'], [429, 'GITHUB_RATE_LIMIT']]) await assert.rejects(new m.PublicSource(async () => response({}, status)).pull('fixture/example', 42), error => error.code === code); });
test('404 policy is absence only after independently confirmed exact-base access', async () => { const paths = []; const source = new m.PublicSource(async url => { paths.push(url); return url.includes('/git/commits/') ? response({ sha: comparison.base }) : response({}, 404); }); assert.equal((await source.policy('fixture/example', comparison.base, '.diffdevil.yml')).status, 'absent'); assert.equal(paths.length, 2); await assert.rejects(new m.PublicSource(async () => response({}, 404)).policy('fixture/example', comparison.base, '.diffdevil.yml'), error => error.code === 'POLICY_ACCESS'); });
test('trusted base-policy UTF-8 is decoded without remote executable content', async () => { const text = 'version: 1\n# Grüße\n'; const source = new m.PublicSource(async () => response({ type: 'file', encoding: 'base64', sha: 'c'.repeat(40), content: Buffer.from(text).toString('base64') })); const result = await source.policy('fixture/example', comparison.base, '.diffdevil.yml'); assert.equal(result.text, text); assert.equal(result.blob, 'c'.repeat(40)); });
test('symlinks, invalid blob identity and over-limit policy bodies are rejected', async () => { for (const value of [{ type: 'symlink', encoding: 'base64', sha: 'c'.repeat(40), content: '' }, { type: 'file', encoding: 'base64', sha: 'not-a-sha', content: '' }, { type: 'file', encoding: 'base64', sha: 'c'.repeat(40), content: Buffer.alloc(256 * 1024 + 1).toString('base64') }]) await assert.rejects(new m.PublicSource(async () => response(value)).policy('fixture/example', comparison.base, '.diffdevil.yml')); });
test('bounded UTF-8 reader accounts for bytes and cancels oversized responses', async () => { assert.equal(await m.boundedText(new Response('éé'), 4), 'éé'); await assert.rejects(m.boundedText(new Response('éé'), 3), error => error.code === 'SOURCE_LIMIT'); await assert.rejects(m.boundedText(new Response(Uint8Array.from([0xff])), 10)); });

test('portable browser export is truly closed and CSP-safe', async () => { const source = await readFile('dist/browser/index.js', 'utf8'); assert.doesNotMatch(source, /\bnew Function\s*\(|\beval\s*\(/u); assert.doesNotMatch(source, /(?:from|import)\s*['"]node:/u); const metadata = JSON.parse(await readFile('dist/browser/metafile.json', 'utf8')); assert.ok(Object.values(metadata.outputs).every(output => output.imports.every(item => !item.external))); });
test('content bundle contains no compiler, parser or heavy policy runtime', async () => { const meta = JSON.parse(await readFile('artifacts/browser-extension/bundle-metafile.json', 'utf8')); const entries = Object.keys(meta.content.inputs); assert.ok(entries.every(name => !/chevrotain|\/policy\/compile|dist\/browser\/index/u.test(name)), entries.join('\n')); const code = await readFile('artifacts/browser-extension/unpacked/content.js'); assert.ok(code.length < 100 * 1024, `Content bundle: ${code.length} bytes`); });
test('manifest confines permissions, executable resources and incognito behavior', async () => { const manifest = JSON.parse(await readFile('apps/browser-extension/manifest.json', 'utf8')); assert.equal(manifest.manifest_version, 3); assert.deepEqual(manifest.permissions, ['storage']); assert.deepEqual(manifest.host_permissions, ['https://api.github.com/*']); assert.equal(manifest.incognito, 'not_allowed'); assert.ok(manifest.web_accessible_resources.flatMap(item => item.resources).every(name => name.endsWith('.svg') || name.endsWith('.woff2'))); assert.doesNotMatch(manifest.content_security_policy.extension_pages, /unsafe-eval/u); assert.equal(manifest.externally_connectable, undefined); });
test('settings document has no Store link or unrelated remote assets', async () => { const html = await readFile('apps/browser-extension/options.html', 'utf8'); assert.doesNotMatch(html, /chromewebstore\.google\.com|fonts\.google|googletagmanager/u); assert.match(html, /privacy\.html/u); });
test('extension package is a deterministic readback of the accepted unpacked receipt', async () => { execFileSync(process.execPath, ['tools/browser-extension-package.mjs'], { stdio: 'pipe' }); const receipt = JSON.parse(await readFile('artifacts/browser-extension/package/package-receipt.json', 'utf8')); assert.equal(receipt.kind, 'diffdevil.browser-extension-package/1'); assert.equal(receipt.archive.members.length, JSON.parse(await readFile('artifacts/browser-extension/build-receipt.json', 'utf8')).files.length); assert.deepEqual(receipt.archive.members.map(member => member.path), [...receipt.archive.members.map(member => member.path)].sort()); });
